### DISCUSSION TITLE
Cloudflare workers

### DISCUSSION THREAD

**Discussion by alexchudnovsky** [nitrojs/nitro#349] [Q&A]
Hi Guys,

I am following the instructions as per 

https://nitro.unjs.io/deploy/providers/cloudflare.html

However, I am getting the error below

Not sure what I am doing wrong 

![screenshot](https://user-images.githubusercontent.com/33717212/179160681-a56d6147-a86d-4504-a410-dca0c7305095.png)

Any help would be appreciated

Cheers,
Alex

**Comment by alexchudnovsky** [comment]
my wrangler.toml file is below

name = "central-files"
type = "javascript"
account_id = "######"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"

**Comment by sduduzog** [comment]
Make sure you're using wrangler v1

Uninstall wrangler v2 => `npm uninstall -g wrangler`

then

`npm install -g @cloudflare/wrangler`

You won't have to change anything for your configuration

## EDIT

After I replied, I actually read up in how to use wrangler v2 and it's actually possible but with minor tweaks to your wrangler.toml [See docs](https://developers.cloudflare.com/workers/wrangler/migration/deprecations/)
Here's my config:
```toml
name = "<my worker name>"
compatibility_date = "2022-08-04"

main = ".output/server/index.mjs"

routes = [{ pattern = "<my custom domain here>", custom_domain = true }]

[site]
bucket = ".output/public"
```

And running `wrangler publish` is enough to deploy
