### DISCUSSION TITLE
CloudFlare Worker (Wrangler) deployment struggling to resolve node modules for Nuxt3

### DISCUSSION THREAD

**Discussion by l-monninger** [nitrojs/nitro#675] [Q&A]
I'm struggling to get `Nuxt3` (w/Nitro) working as a CloudFlare Worker (Wrangler) deployment. It have my `wrangler.toml` configured as:
```toml
name = "<redacted>"
type = "javascript"
account_id = "<redacted>"
workers_dev = true
compatibility_date = "2022-09-10"
main = "./.output/server/index.mjs"

[site]
bucket = "./.output/public"

[build]
command = "true"
upload.format = "service-worker"
```

However, this fails; it appears because `node_modules` is not successfully internalized:

```log
.output/server/chunks/app/_nuxt/error-404.0ef263a0.mjs:2:85: ERROR:
  Could not resolve "vue"
  .output/server/chunks/app/_nuxt/error-404.0ef263a0.mjs:4:7: ERROR:
  Could not resolve "ohmyfetch"
  .output/server/chunks/app/_nuxt/error-404.0ef263a0.mjs:15:7: ERROR:
  Could not resolve "node-fetch-native/polyfill"
  .output/server/chunks/app/_nuxt/error-404.0ef263a0.mjs:16:7: ERROR:
  Could not resolve "http"
  .output/server/chunks/app/_nuxt/error-404.0ef263a0.mjs:17:7: ERROR:
  Could not resolve "https"
```

Any thoughts on how to resolve? I'm asking in the Nuxt community as well.
