### DISCUSSION TITLE
How to do CRON / schedule function

### DISCUSSION THREAD

**Discussion by iBobik** [nitrojs/nitro#846] [Q&A]
I use server function in Nuxt deployed to Firebase function. How to regularly run some specific function?

I understand [this guide](https://firebase.google.com/docs/functions/schedule-functions), but I can not imagine how to use it with that Nitro's compilation magic.

```
exports.scheduledFunction = functions.pubsub.schedule('every 5 minutes').onRun((context) => {
  console.log('This will be run every 5 minutes!');
  return null;
});
```

**Comment by robokozo** [comment]
I think you'd want to deploy your CRON job as its own cloud function - separate from your website. This way itll be de-coupled and deployable without touching your nuxt code.

**Comment by iBobik** [comment]
Is it possible to deploy this function from the same repository by one firebase deploy call? I have not found how to have multiple functions specified in the firebase.json.Honza Pobořil💬Signal25. 2. 2023 v 5:27, John ***@***.***>:﻿
I think you'd want to deploy your CRON job as its own cloud function - separate from your website. This way itll be de-coupled and deployable without touching your nuxt code.

**Comment by iBobik** [comment]
I have the same question for Cloudflare Pages.

Is it really impossible to add custom handlers to the exported worker module?

**Comment by stafyniaksacha** [comment]
You can create a nitro endpoint (you may need to use an authorization header), and call this one on the desired schedule.

Github Action can be used like this

```yaml
name: Scheduled HTTP Call
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: tyrrrz/action-http-request@master
        with:
          url: https://example.com/api/task
          method: POST
          headers: |
            Content-Type: application/json
            Authorization: Token XXXX
          body: |
            {
              "foo": "bar"
            }
```
