### ISSUE TITLE
Production cert and key should support filesystem paths

### ISSUE THREAD

**Issue by pi0** [nitrojs/nitro#749]
Ref: https://github.com/nuxt/nuxt.js/issues/12827

Running a production server with SSL needs the `NITRO_SSL_CERT` and `NITRO_SSL_KEY` to be from filesystem.

As a workaround (UNIX and Mac), we can use:

```
NITRO_SSL_CERT="`cat path/to/cert.pem`" NITRO_SSL_KEY="`cat path/to/key.pem`" node .output/server/index.mjs
```

**Comment by dataexcess** [comment]
Amazing that worked :D thank you for the quick reply

**Comment by dataexcess** [comment]
woops I should make a new ticket for this I guess

**Comment by pi0** [comment]
You can use a `server.sh` script that starts the server with SSL.

```js
#!/bin/bash
NITRO_SSL_CERT="`cat path/to/cert.pem`" NITRO_SSL_KEY="`cat path/to/key.pem`" node .output/server/index.mjs
```

"start": "./server.sh"

**Comment by dataexcess** [comment]
Works like a charm ✨ thank you!
And I can set the PORT and HOST var before, perfect.
"start": "HOST=localhost PORT=3001 ./server.sh"

**Comment by alex-key** [comment]
@pi0 Could it be just as simple as this:
```
import { readFileSync } from "node:fs";
import { resolve } from "pathe";

...

let cert = process.env.NITRO_SSL_CERT;
let key = process.env.NITRO_SSL_KEY;

if (cert && key) {
  cert = readFileSync(resolve(cert), "utf8");
  key = readFileSync(resolve(key), "utf8");
}
```

**Comment by ananthachetan** [comment]
Any idea when the fix will be available?

**Comment by rudolfbyker** [comment]
For me, even when specifying `NITRO_SSL_KEY` and `NITRO_SSL_CERT`, it always starts as `HTTP` rather than `HTTPS`.

**Comment by Ena-Heleneto** [comment]
Do all your certificates have the pem suffix.
My certificate looks like this
/home/cer/*****_server.key
/home/cer/*****_server.crt

My error message is
```
node:internal/tls/secure-context:70
    context.setCert(cert);
            ^

Error: error:0480006C:PEM routines::no start line
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:182:5)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at file:///app/.output/server/chunks/runtime.mjs:14231:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25) {
  library: 'PEM routines',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}

Node.js v18.20.3
```

My docker compose configuration is
```
version: '3.8'

services:
  HW_Maintenance_Web:
    image: swr.cn-east-3.myhuaweicloud.com/jst/hw_maintenance_web:latest
    container_name: hw-maintenance-web
    environment:
      env_flag: 'production'
      NITRO_SSL_KEY: '/home/cer/***_server.key'
      NITRO_SSL_CERT: '/home/cer/***_server.crt'
    ports:
      - 80:3000
```

What should I do? thanks
